Added http submodules support to init script and updated docs
Change-Id: I1043b642d0b69fbf559291dfe1aeb099645e1d39

Former-commit-id: c915eb231f306031f70cf169aace2e95adf2800a

diff --git a/init b/init
--- a/init
+++ b/init
@@ -1,11 +1,17 @@
 #!/bin/bash
 
-if [ ! -e "veles/znicz/.project" -o ! -e libSoundFeatureExtraction/.project ]; then
-	user=$(git remote -v | grep -oE '//[^@]+' -m1 | cut -c3-)
-    sed -i "/$user/b; s/ssh:\/\//ssh:\/\/$user@/g" .gitmodules
-    while ! git submodule update --init; do
-        echo 'Failed to checkout submodules, retrying...'
-    done
+if [ ! -e "veles/znicz/__init__.py" -o ! -e libSoundFeatureExtraction/.project -o ! -e mastodon/pom.xml ]; then
+  if git remote -v | grep ssh:// >/dev/null; then
+    host=$(git remote -v|head -n 1|cut -f 2|cut -d ' ' -f 1|sed -e 's/ssh:\/\///' -e 's/Veles$//' -e 's/\//\\\//g')
+    sed -i "s/alserver.rnd.samsung.ru:29418\//$host/g" .gitmodules
+  else
+    # assuming http://
+    host=$(git remote -v|head -n 1|cut -f 2|cut -d ' ' -f 1|sed -e 's/http:\/\///' -e 's/Veles$//' -e 's/\//\\\//g')
+    sed -i "s/ssh:\/\/alserver.rnd.samsung.ru:29418\//http:\/\/$host/g" .gitmodules
+  fi
+  while ! git submodule update --init; do
+    echo 'Failed to checkout submodules, retrying...'
+  done
 else
     git submodule update
 fi
